# Generated by Django 2.2.4 on 2019-09-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190905_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=500, null=True, verbose_name='Yorum'),
        ),
    ]
