# Generated by Django 2.2.4 on 2019-09-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190905_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(default=2, max_length=500, verbose_name='Yorum'),
            preserve_default=False,
        ),
    ]
