# Generated by Django 2.2.4 on 2019-09-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190906_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
